export const DropDownNum = [
  { value: '1', label: '1' },
  { value: '2', label: '2' },
  { value: '3', label: '3' },
  { value: '4', label: '4' },
  { value: '5', label: '5' },
  { value: '6', label: '6' },
  { value: '7', label: '7' },
  { value: '8', label: '8' },
  { value: '9', label: '9' },
  { value: '10', label: '10' },
  { value: '11', label: '11' },
  { value: '12', label: '12' },
  { value: '13', label: '13' },
  { value: '14', label: '14' },
  { value: '15', label: '15' }
]

export const DropDownTime = [
  { value: 'AM 9:00', label: 'AM 9:00' },
  { value: 'AM 9:30', label: 'AM 9:30' },
  { value: 'AM 10:00', label: 'AM 10:00' },
  { value: 'AM 10:30', label: 'AM 10:30' },
  { value: 'AM 11:00', label: 'AM 11:00' },
  { value: 'AM 11:30', label: 'AM 11:30' },
  { value: 'PM 12:00', label: 'PM 12:00' },
  { value: 'PM 12:30', label: 'PM 12:30' },
  { value: 'PM 1:00', label: 'PM 1:00' },
  { value: 'PM 1:30', label: 'PM 1:30' },
  { value: 'PM 2:00', label: 'PM 2:00' },
  { value: 'PM 2:30', label: 'PM 2:30' },
  { value: 'PM 3:00', label: 'PM 3:00' },
  { value: 'PM 3:30', label: 'PM 3:30' },
  { value: 'PM 4:00', label: 'PM 4:00' },
  { value: 'PM 4:30', label: 'PM 4:30' },
  { value: 'PM 5:00', label: 'PM 5:00' },
  { value: 'PM 5:30', label: 'PM 5:30' },
  { value: 'PM 6:00', label: 'PM 6:00' },
  { value: 'PM 6:30', label: 'PM 6:30' },
  { value: 'PM 7:00', label: 'PM 7:00' },
  { value: 'PM 7:30', label: 'PM 7:30' },
]

export const DropDownTime2 = [
  { value: '전일가능', label: '전일가능' },
  { value: 'AM 9:00', label: 'AM 9:00' },
  { value: 'AM 9:30', label: 'AM 9:30' },
  { value: 'AM 10:00', label: 'AM 10:00' },
  { value: 'AM 10:30', label: 'AM 10:30' },
  { value: 'AM 11:00', label: 'AM 11:00' },
  { value: 'AM 11:30', label: 'AM 11:30' },
  { value: 'PM 12:00', label: 'PM 12:00' },
  { value: 'PM 12:30', label: 'PM 12:30' },
  { value: 'PM 1:00', label: 'PM 1:00' },
  { value: 'PM 1:30', label: 'PM 1:30' },
  { value: 'PM 2:00', label: 'PM 2:00' },
  { value: 'PM 2:30', label: 'PM 2:30' },
  { value: 'PM 3:00', label: 'PM 3:00' },
  { value: 'PM 3:30', label: 'PM 3:30' },
  { value: 'PM 4:00', label: 'PM 4:00' },
  { value: 'PM 4:30', label: 'PM 4:30' },
  { value: 'PM 5:00', label: 'PM 5:00' },
  { value: 'PM 5:30', label: 'PM 5:30' },
  { value: 'PM 6:00', label: 'PM 6:00' },
  { value: 'PM 6:30', label: 'PM 6:30' },
  { value: 'PM 7:00', label: 'PM 7:00' },
  { value: 'PM 7:30', label: 'PM 7:30' },
]

export const DropDowncharger = [
  { value: "선택", label: "선택" },
  { value: '조동희', label: '조동희' },
  { value: '김철수', label: '김철수' },
  { value: '조수환', label: '조수환' },
  { value: '김수진', label: '김수진' },
  { value: '류주희', label: '류주희' },
  { value: '박정준', label: '박정준' },
  { value: '박지혜', label: '박지혜' },
  { value: '이한나', label: '이한나' },
  { value: '최윤경', label: '최윤경' },
  { value: '이요한', label: '이요한' }
]

export const DropDownVisitPath = [
  { value: '웹사이트', label: '웹사이트' },
  { value: '박람회페이지', label: '박람회페이지' },
  { value: '업체소개', label: '업체소개' },
  { value: '전화상담', label: '전화상담' },
  { value: '카톡상담', label: '카톡상담' },
  { value: '방문상담', label: '방문상담' },
  { value: '지인소개', label: '지인소개' },
  { value: '사원지인', label: '사원지인' }
]

export const DropDownTourLocation = [
  { value: "여행지선택", label: "여행지선택" },
  { value: '코사무이', label: '코사무이' },
  { value: '푸켓', label: '푸켓' },
  { value: '카오락', label: '카오락' },
  { value: '크라비', label: '크라비' },
  { value: '다낭', label: '다낭' },
  { value: '나트랑', label: '나트랑' },
  { value: '푸꾸옥', label: '푸꾸옥' },
  { value: '세부', label: '세부' },
  { value: '보라카이', label: '보라카이' },
  { value: '괌', label: '괌' },
  { value: '뉴질랜드', label: '뉴질랜드' },
  { value: '동유럽', label: '동유럽' },
  { value: '두바이', label: '두바이' },
  { value: '랑카위', label: '랑카위' },
  { value: '모두투어', label: '모두투어' },
  { value: '모리셔스', label: '모리셔스' },
  { value: '몰디브', label: '몰디브' },
  { value: '미본토', label: '미본토' },
  { value: '발리', label: '발리' },
  { value: '베트남', label: '베트남' },
  { value: '사이판', label: '사이판' },
  { value: '서유럽', label: '서유럽' },
  { value: '세이쉘', label: '세이쉘' },
  { value: '스페인', label: '스페인' },
  { value: '싱가폴', label: '싱가폴' },
  { value: '유럽', label: '유럽' },
  { value: '일본', label: '일본' },
  { value: '제주도', label: '제주도' },
  { value: '중국(하이난)', label: '중국(하이난)' },
  { value: '중남미', label: '중남미' },
  { value: '지중해', label: '지중해' },
  { value: '칸쿤', label: '칸쿤' },
  { value: '캐나다', label: '캐나다' },
  { value: '코타키나바루', label: '코타키나바루' },
  { value: '타히티', label: '타히티' },
  { value: '태국', label: '태국' },
  { value: '필리핀', label: '필리핀' },
  { value: '하나투어', label: '하나투어' },
  { value: '하와이', label: '하와이' },
  { value: '호주', label: '호주' },
  { value: '홍콩', label: '홍콩' },
  { value: '기타', label: '기타' }
]

export const DropDownAirline = [
  { value: "항공사선택", label: "항공사선택" },
  { value: 'KE 대한항공', label: 'KE 대한항공' },
  { value: '5J 세부퍼시픽항공', label: '5J 세부퍼시픽항공' },
  { value: '7C 제주항공', label: '7C 제주항공' },
  { value: 'AA 아메리칸항공', label: 'AA 아메리칸항공' },
  { value: 'AC 캐나다항공', label: 'AC 캐나다항공' },
  { value: 'AF 에어프랑스', label: 'AF 에어프랑스' },
  { value: 'AM 아에로멕시코', label: 'AM 아에로멕시코' },
  { value: 'AY 핀에어', label: 'AY 핀에어' },
  { value: 'AZ ITA항공', label: 'AZ ITA항공' },
  { value: 'BA 영국항공', label: 'BA 영국항공' },
  { value: 'BX 에어부산', label: 'BX 에어부산' },
  { value: 'CI 중화항공', label: 'CI 중화항공' },
  { value: 'CX 캐세이퍼시픽항공', label: 'CX 캐세이퍼시픽항공' },
  { value: 'CZ 중국남방항공', label: 'CZ 중국남방항공' },
  { value: 'DL 델타항공', label: 'DL 델타항공' },
  { value: 'EK 에미레이트항공', label: 'EK 에미레이트항공' },
  { value: 'EY 에티하드항공', label: 'EY 에티하드항공' },
  { value: 'GA 가루다인도네시아', label: 'GA 가루다인도네시아' },
  { value: 'HA 하와이안항공', label: 'HA 하와이안항공' },
  { value: 'JL 일본항공', label: 'JL 일본항공' },
  { value: 'JQ 젯스타항공', label: 'JQ 젯스타항공' },
  { value: 'KL 네덜란드항공', label: 'KL 네덜란드항공' },
  { value: 'LH 루프트한자독일항공', label: 'LH 루프트한자독일항공' },
  { value: 'LJ 진에어항공', label: 'LJ 진에어 항공' },
  { value: 'LO 폴란드항공', label: 'LO 폴란드항공' },
  { value: 'LX 스위스국제항공', label: 'LX 스위스국제항공' },
  { value: 'MH 말레이시아 항공', label: 'MH 말레이시아 항공' },
  { value: 'MK 모리셔스항공', label: 'MK 모리셔스항공' },
  { value: 'MU 중국동방항공', label: 'MU 중국동방항공' },
  { value: 'OK 체코항공', label: 'OK 체코항공' },
  { value: 'OZ 아시아나', label: 'OZ 아시아나' },
  { value: 'PG 방콕항공', label: 'PG 방콕항공' },
  { value: 'PR 필리핀항공', label: 'PR 필리핀항공' },
  { value: 'QF 콴타스호주항공', label: 'QF 콴타스호주항공' },
  { value: 'QR 카타르항공', label: 'QR 카타르항공' },
  { value: 'SQ 싱가폴항공', label: 'SQ 싱가폴항공' },
  { value: 'TG 타이항공', label: 'TG 타이항공' },
  { value: 'TK 터키항공', label: 'TK 터키항공' },
  { value: 'TR 스쿠트항공', label: 'TR 스쿠트항공' },
  { value: 'TW 티웨이항공', label: 'TW 티웨이항공' },
  { value: 'UA 유나이티드항공', label: 'UA 유나이티드항공' },
  { value: 'UL 스리랑카항공', label: 'UL 스리랑카항공' },
  { value: 'UO 홍콩익스프레스항공', label: 'UO 홍콩익스프레스항공' },
  { value: 'VJ 비엣젯항공', label: 'VJ 비엣젯항공' },
  { value: 'VN 베트남항공', label: 'VN 베트남항공' },
  { value: 'WS 웨스트젯', label: 'WS 웨스트젯' },
  { value: 'ZE 이스타 항공', label: 'ZE 이스타 항공' }
]

export const DropDownLandCompany = [
  { value: "랜드사선택", label: "랜드사선택" },
  { value: "007", label: "007" },
  { value: "A.U.M", label: "A.U.M" },
  { value: "FT타이", label: "FT타이" },
  { value: "GRM", label: "GRM" },
  { value: "H투어", label: "H투어" },
  { value: "IMT", label: "IMT" },
  { value: "KTB", label: "KTB" },
  { value: "K투어", label: "K투어" },
  { value: "K투어동남아", label: "K투어동남아" },
  { value: "LTB", label: "LTB" },
  { value: "MMD", label: "MMD" },
  { value: "SJ 몰디브", label: "SJ 몰디브" },
  { value: "SP 몰디브", label: "SP 몰디브" },
  { value: "SS투어", label: "SS투어" },
  { value: "TFK", label: "TFK" },
  { value: "TS트래블", label: "TS트래블" },
  { value: "VIP항공", label: "VIP항공" },
  { value: "가자하와이", label: "가자하와이" },
  { value: "고객직접 발권", label: "고객직접 발권" },
  { value: "고려투어몰", label: "고려투어몰" },
  { value: "고몰디브", label: "고몰디브" },
  { value: "골든홀리데이", label: "골든홀리데이" },
  { value: "굿초이스투어", label: "굿초이스투어" },
  { value: "네오코리아", label: "네오코리아" },
  { value: "노랑풍선", label: "노랑풍선" },
  { value: "다이나믹 괌", label: "다이나믹 괌" },
  { value: "다이나믹투어", label: "다이나믹투어" },
  { value: "대아투어", label: "대아투어" },
  { value: "대한항공", label: "대한항공" },
  { value: "더랜드", label: "더랜드" },
  { value: "델피노투어", label: "델피노투어" },
  { value: "두리두바이", label: "두리두바이" },
  { value: "드림링스", label: "드림링스" },
  { value: "드림티앤이", label: "드림티앤이" },
  { value: "랜드로그인", label: "랜드로그인" },
  { value: "랜드아이콘", label: "랜드아이콘" },
  { value: "렛츠", label: "렛츠" },
  { value: "리조트마케팅", label: "리조트마케팅" },
  { value: "마이리얼트립", label: "마이리얼트립" },
  { value: "모두투어", label: "모두투어" },
  { value: "몰디브넷", label: "몰디브넷" },
  { value: "바캉스", label: "바캉스" },
  { value: "빅프라임투어", label: "빅프라임투어" },
  { value: "스핀", label: "스핀" },
  { value: "스핀투어", label: "스핀투어" },
  { value: "써니", label: "써니" },
  { value: "어바웃유럽", label: "어바웃유럽" },
  { value: "에어부산", label: "에어부산" },
  { value: "여행을찾다", label: "여행을찾다" },
  { value: "여행이지", label: "여행이지" },
  { value: "예스", label: "예스" },
  { value: "예스투어", label: "예스투어" },
  { value: "오리엔탈", label: "오리엔탈" },
  { value: "온라인투어", label: "온라인투어" },
  { value: "와이페이모어", label: "와이페이모어" },
  { value: "요금미정", label: "요금미정" },
  { value: "울트라재팬", label: "울트라재팬" },
  { value: "원더풀투어", label: "원더풀투어" },
  { value: "웹투어", label: "웹투어" },
  { value: "유나이티드에이젼시(항공)", label: "유나이티드에이젼시(항공)" },
  { value: "유로자전거나라", label: "유로자전거나라" },
  { value: "유앤미", label: "유앤미" },
  { value: "이투아리스", label: "이투아리스" },
  { value: "인터파크", label: "인터파크" },
  { value: "제주OK렌트카", label: "제주OK렌트카" },
  { value: "제주항공", label: "제주항공" },
  { value: "젠몰디브", label: "젠몰디브" },
  { value: "진에어", label: "진에어" },
  { value: "참좋은여행", label: "참좋은여행" },
  { value: "창투어", label: "창투어" },
  { value: "최윤경-토파스", label: "최윤경-토파스" },
  { value: "최윤경-토파스발권", label: "최윤경-토파스발권" },
  { value: "카바나", label: "카바나" },
  { value: "콩코드", label: "콩코드" },
  { value: "타이항공", label: "타이항공" },
  { value: "탑투어", label: "탑투어" },
  { value: "토성항공", label: "토성항공" },
  { value: "투어티라", label: "투어티라" },
  { value: "트래벌비즈", label: "트래벌비즈" },
  { value: "티웨이", label: "티웨이" },
  { value: "파크우드", label: "파크우드" },
  { value: "팍스투어", label: "팍스투어" },
  { value: "퍼시픽", label: "퍼시픽" },
  { value: "퍼시픽유럽", label: "퍼시픽유럽" },
  { value: "퍼플 동남아", label: "퍼플 동남아" },
  { value: "퍼플하오이 동남아", label: "퍼플하오이 동남아" },
  { value: "퍼플하와이", label: "퍼플하와이" },
  { value: "프라이데이", label: "프라이데이" },
  { value: "하나몰디브", label: "하나몰디브" },
  { value: "하나투어", label: "하나투어" },
  { value: "하이투어", label: "하이투어" },
  { value: "허니문마케팅", label: "허니문마케팅" },
  { value: "호텔패스", label: "호텔패스" }
]

export const DropDownDepositType = [
  { value: '현금', label: '현금' },
  { value: '무통장입금', label: '무통장입금' },
  { value: '신용카드', label: '신용카드' },
  { value: '카드+입금', label: '카드+입금' },
  { value: '수표입금', label: '수표입금' }
]

export const DropDownDeliveryType = [
  { value: '카톡', label: '카톡' },
  { value: '전화', label: '전화' }
]

export const DropDownCompanyPay = [
  { value: '워킹', label: '워킹' },
  { value: '고객소개', label: '고객소개' },
  { value: '창원점', label: '창원점' },
  { value: '창원리베라', label: '창원리베라' },
  { value: '협회', label: '협회' },
  { value: '협회박람회', label: '협회박람회' },
  { value: '웨딩쿨', label: '웨딩쿨' },
  { value: '웨딩쿨박람회', label: '웨딩쿨박람회' },
  { value: '웨딩쿨하우스박람회', label: '웨딩쿨하우스박람회' },
  { value: '비앤비', label: '비앤비' },
  { value: '비앤비박람회', label: '비앤비박람회' },
  { value: '비앤비박람회-세이', label: '비앤비박람회-세이' },
  { value: '감성공작소', label: '감성공작소' },
  { value: '감성공작소박람회', label: '감성공작소박람회' },
  { value: '비마인드', label: '비마인드' },
  { value: '비마인드박람회', label: '비마인드박람회' },
  { value: '결사모', label: '결사모' },
  { value: '웨딩K', label: '웨딩K' },
  { value: '웨딩홀', label: '웨딩홀' },
  { value: '웨딩업체', label: '웨딩업체' },
  { value: '사원지인', label: '사원지인' },
  { value: '박람회', label: '박람회' },
  { value: '웨딩세이', label: '웨딩세이' },
  { value: '웨딩세이-박람회', label: '웨딩세이-박람회' },
  { value: '웨딩데이', label: '웨딩데이' },
  { value: '커스텀', label: '커스텀' },
  { value: '세위드', label: '세위드' },
  { value: '럭스에디션', label: '럭스에디션' },
  { value: '드웨딩', label: '드웨딩' },
  { value: '웨딩스타', label: '웨딩스타' },
  { value: '기타', label: '기타' }
]

export const DropDownTourPeriodNightType = [
  { value: '선택', label: '선택' },
  { value: '1박', label: '1박' },
  { value: '2박', label: '2박' },
  { value: '3박', label: '3박' },
  { value: '4박', label: '4박' },
  { value: '5박', label: '5박' },
  { value: '6박', label: '6박' },
  { value: '7박', label: '7박' },
  { value: '8박', label: '8박' },
  { value: '9박', label: '9박' },
  { value: '10박', label: '10박' },
  { value: '11박', label: '11박' },
  { value: '12박', label: '12박' },
  { value: '13박', label: '13박' }
]

export const DropDownTourPeriodDayType = [
  { value: '선택', label: '선택' },
  { value: '5일', label: '5일' },
  { value: '6일', label: '6일' },
  { value: '7일', label: '7일' },
  { value: '8일', label: '8일' },
  { value: '9일', label: '9일' },
  { value: '10일', label: '10일' },
  { value: '11일', label: '11일' },
  { value: '12일', label: '12일' },
  { value: '13일', label: '13일' },
  { value: '14일', label: '14일' },
  { value: '15일', label: '15일' }
]

export const DropDownPackageType = [
  { value: '선택', label: '선택' },
  { value: '셔틀팩', label: '셔틀팩' },
  { value: '시티팩', label: '시티팩' },
  { value: '베이직팩', label: '베이직팩' },
  { value: '스마트플러스', label: '스마트플러스' },
  { value: '60일 미만', label: '60일 미만' },
  { value: '45일 미만', label: '45일 미만' },
  { value: '30일 미만', label: '30일 미만' },
  { value: '트랜스퍼', label: '트랜스퍼' },
  { value: '정글투어', label: '정글투어' },
  { value: '웨딩스냅', label: '웨딩스냅' },
  { value: '오전도착비행기', label: '오전도착비행기' },
]

export const DropDownSeasonType = [
  { value: '선택', label: '선택' },
  { value: '하이시즌', label: '하이시즌' },
  { value: '픽시즌', label: '픽시즌' },
  { value: '블랫아웃', label: '블랫아웃' }
]

export const DropDownUserLevel = [
  { value: '선택', label: '선택' },
  { value: '신규', label: '신규' },
  { value: '실버', label: '실버' },
  { value: '골드', label: '골드' },
  { value: 'VIP', label: 'VIP' },
  { value: 'VVIP', label: 'VVIP' },
  { value: '탈퇴', label: '탈퇴' }
]